# Generated by Django 3.1.5 on 2021-02-02 04:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Client', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='OffersHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_time_generated', models.DateTimeField(auto_now_add=True)),
                ('date_time_expire', models.DateTimeField()),
                ('is_expired', models.BooleanField(default=False)),
                ('client', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='client_offers', to='Client.client')),
            ],
            options={
                'db_table': 'offers_history',
            },
        ),
        migrations.CreateModel(
            name='Offers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('partner_id', models.IntegerField(blank=True)),
                ('partner_name', models.CharField(blank=True, max_length=200)),
                ('value', models.FloatField(null=True)),
                ('tax_rate_percent_montly', models.FloatField(null=True)),
                ('total_value', models.FloatField(null=True)),
                ('installments', models.IntegerField(null=True)),
                ('history', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fk_offers_history', to='Offers.offershistory')),
            ],
            options={
                'db_table': 'offers',
            },
        ),
    ]
