version: '3.3'
services:

  db:
    image: mysql:5.7.20
    container_name: Mysql
    restart: always
    environment:
      MYSQL_DATABASE: 'db'
      MYSQL_USER: 'user'
      MYSQL_PASSWORD: 'password'
      MYSQL_ROOT_PASSWORD: 'password'
    ports:
      - '3306:3306'
    expose:
      - '3306'
    volumes:
      - my-db:/var/lib/mysql
      - ./db:/docker-entrypoint-initdb.
      - ./db/initial.sql:/docker-entrypoint-initdb.d/initial.sql

  redis:
    image: "redis:alpine"
    container_name: Redis
    # command: redis-server --requirepass password
    ports:
      - '6379:6379'

  api:
    build:
      context: ./MarketPlace/
      dockerfile: Dockerfile
    container_name: API
    command: bash -c "python /MarketPlace/manage.py migrate "
    ports: 
      - "8000:8000"
    depends_on: 
      - db

volumes:
  my-db: