version: '3.7'
services:
  db:
    image: mysql:5.7
    container_name: Mysql
    restart: always
    environment:
      - MYSQL_DATABASE=market_place
      - MYSQL_ROOT_PASSWORD=password
    ports:
      - '3306:3306'
    volumes:
      - my-db:/var/lib/mysql
      - ./db:/docker-entrypoint-initdb.
      - ./db/initial.sql:/docker-entrypoint-initdb.d/initial.sql
  redis:
    image: "redis:alpine"
    container_name: Redis
    restart: always
    ports:
      - '6379:6379'
volumes:
  my-db: