# Generated by Django 3.1.5 on 2021-02-02 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(blank=True, max_length=200)),
                ('cpf', models.CharField(blank=True, max_length=200)),
                ('email', models.EmailField(blank=True, max_length=200)),
                ('telephone', models.CharField(blank=True, max_length=200)),
                ('net_salary', models.FloatField(null=True)),
            ],
            options={
                'db_table': 'client',
            },
        ),
    ]
