# Generated by Django 3.1.5 on 2021-01-31 17:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Client', '0003_auto_20210130_2047'),
        ('Offers', '0008_offers_installments'),
    ]

    operations = [
        migrations.CreateModel(
            name='Propostal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_send', models.DateField(blank=True)),
                ('date_received', models.DateField(auto_now_add=True)),
                ('propostal_id', models.IntegerField(null=True)),
                ('message', models.TextField(blank=True)),
                ('client', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='client_propostal', to='Client.client')),
                ('offer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='offer_propostal', to='Offers.offers')),
            ],
        ),
    ]
