# Generated by Django 3.1.5 on 2021-02-02 21:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Propostal', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='propostal',
            table='propostals',
        ),
    ]
