# Generated by Django 3.1.5 on 2021-01-30 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Offers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('partner_id', models.IntegerField(blank=True)),
                ('partner_name', models.CharField(blank=True, max_length=200)),
                ('offer_value', models.FloatField(null=True)),
                ('installments', models.IntegerField(null=True)),
                ('monthly_interest', models.FloatField(null=True)),
                ('amount', models.FloatField(null=True)),
            ],
            options={
                'db_table': 'offers',
            },
        ),
    ]
