# Generated by Django 3.1.5 on 2021-01-30 18:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Offers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OffersHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_time', models.DateTimeField(auto_now_add=True)),
                ('quantity', models.IntegerField(null=True)),
            ],
            options={
                'db_table': 'offers_history',
            },
        ),
        migrations.AddField(
            model_name='offers',
            name='history',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, related_name='fk_offers_history', to='Offers.offershistory'),
            preserve_default=False,
        ),
    ]
