# Generated by Django 3.1.5 on 2021-01-30 19:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Offers', '0002_auto_20210130_1547'),
    ]

    operations = [
        migrations.RenameField(
            model_name='offers',
            old_name='installments',
            new_name='tax_rate_percent_montly',
        ),
        migrations.RenameField(
            model_name='offers',
            old_name='amount',
            new_name='total_value',
        ),
        migrations.RenameField(
            model_name='offers',
            old_name='monthly_interest',
            new_name='value',
        ),
        migrations.RenameField(
            model_name='offershistory',
            old_name='date_time',
            new_name='date_time_generated',
        ),
        migrations.RemoveField(
            model_name='offers',
            name='offer_value',
        ),
        migrations.AddField(
            model_name='offershistory',
            name='date_time_expire',
            field=models.DateTimeField(default=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='offershistory',
            name='is_expired',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='offers',
            name='history',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='fk_offers_history', to='Offers.offershistory'),
        ),
    ]
