# Generated by Django 3.1.5 on 2021-01-30 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Offers', '0003_auto_20210130_1638'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offers',
            name='tax_rate_percent_montly',
            field=models.FloatField(null=True),
        ),
    ]
