# Generated by Django 3.1.5 on 2021-01-30 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Offers', '0004_auto_20210130_1724'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offers',
            name='tax_rate_percent_montly',
            field=models.IntegerField(null=True),
        ),
    ]
