# Generated by Django 3.1.5 on 2021-01-30 22:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Client', '0001_initial'),
        ('Offers', '0006_auto_20210130_1908'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='offershistory',
            name='quantity',
        ),
        migrations.AddField(
            model_name='offershistory',
            name='client',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='client_offers', to='Client.client'),
        ),
        migrations.AlterField(
            model_name='offers',
            name='history',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fk_offers_history', to='Offers.offershistory'),
        ),
    ]
