# Generated by Django 3.1.5 on 2021-01-30 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Offers', '0007_auto_20210130_1942'),
    ]

    operations = [
        migrations.AddField(
            model_name='offers',
            name='installments',
            field=models.IntegerField(null=True),
        ),
    ]
